version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/customerdb;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - h2-data:/data
    networks:
      - customer-network
    restart: unless-stopped

networks:
  customer-network:
    driver: bridge

volumes:
  h2-data: