name: CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with coverage
      run: ./gradlew test jacocoTestReport
      
    - name: Upload test coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-reports
        path: build/reports/jacoco/
        
    - name: OWASP Dependency Check
      run: ./gradlew dependencyCheckAnalyze
      
    - name: Upload dependency check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: build/reports/dependency-check-report.html